webserver:
  image: "ghcr.io/gchazot/oneevent-sandbox:latest"
  replicas: 1
  hostnames: []

db:
  credentials:
    secretName: db-secret-credentials
    database: myDbName
    username: myDbUser
    password: some-random-password

socialAuths:
  - name: GOOGLE_OAUTH2
    key: ""
    secret: ""
  - name: GITHUB
    key: ""
    secret: ""
  - name: FACEBOOK
    key: ""
    secret: ""
